### ISSUE TITLE
Problem running catkin_make

### ISSUE THREAD

**Issue by ltf1001** [Zhefan-Xu/map_manager#3]
Hello author! Thank you very much for opening up this project. It is very perfect. When I ran your code according to instructions, there was an error that I couldn't solve.
The error:
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "onboard_detector"
  with any of the following names:

    onboard_detectorConfig.cmake
    onboard_detector-config.cmake

  Add the installation prefix of "onboard_detector" to CMAKE_PREFIX_PATH or
  set "onboard_detector_DIR" to a directory containing one of the above
  files.  If "onboard_detector" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  map_manager/CMakeLists.txt:12 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/oem/Fanzhe Xu/autolar/build/CMakeFiles/CMakeOutput.log".
See also "/home/oem/Fanzhe Xu/autolar/build/CMakeFiles/CMakeError.log".
 When running catkin_ make .There is an issue with make. I tried using the command(sudo apt-get install ros-noetic-onboard-detector), but it still couldn't solve the problem

**Comment by Zhefan-Xu** [comment]
Please check this for onboard_detector: https://github.com/Zhefan-Xu/onboard_detector/tree/598ee24796c4ef387c7fcf2f0ccea1039ffaedbd


Be sure to check the instructions and its link. Also I suggest to work with our entire framework that will be more convenient: https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy

**Comment by ltf1001** [comment]
Thank you very much for your help. The effect is excellent.
