### ISSUE TITLE
关于移动目标预测

### ISSUE THREAD

**Issue by lichardh** [Zhefan-Xu/map_manager#4]
您好，在您的论文“AAreal-time dynamic obstacle tracking and mapping system for UAV navigation and collision avoidance with an RGB-D camera“中提到了用markov chain进行目标移动预测的工作，请问这一部分的代码在哪个package里面呢，我没有找到。谢谢！

**Comment by Zhefan-Xu** [comment]
@lichardh 你好，这个目前还没有implement到main branch，但是源码在main-uv branch上有。

**Comment by lichardh** [comment]
好的，十分感谢。
