### ISSUE TITLE
fatal error: map_manager/CheckPosCollision.h: No such file or directory

### ISSUE THREAD

**Issue by Archie945** [Zhefan-Xu/map_manager#5]
当我完全按照您的教程安装时，收到了找不到这个头文件的错误。
[ 26%] Building CXX object CERLAB-UAV-Autonomy/map_manager/CMakeFiles/map_manager.dir/include/map_manager/occupancyMap.cpp.o
In file included from /home/nvidia/catkin_ws/src/CERLAB-UAV-Autonomy/map_manager/include/map_manager/occupancyMap.cpp:6:0:
/home/nvidia/catkin_ws/src/CERLAB-UAV-Autonomy/map_manager/include/map_manager/occupancyMap.h:25:10: fatal error: map_manager/CheckPosCollision.h: No such file or directory
 #include <map_manager/CheckPosCollision.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CERLAB-UAV-Autonomy/map_manager/CMakeFiles/map_manager.dir/build.make:62: recipe for target 'CERLAB-UAV-Autonomy/map_manager/CMakeFiles/map_manager.dir/include/map_manager/occupancyMap.cpp.o' failed
make[2]: *** [CERLAB-UAV-Autonomy/map_manager/CMakeFiles/map_manager.dir/include/map_manager/occupancyMap.cpp.o] Error 1
CMakeFiles/Makefile2:4193: recipe for target 'CERLAB-UAV-Autonomy/map_manager/CMakeFiles/map_manager.dir/all' failed
make[1]: *** [CERLAB-UAV-Autonomy/map_manager/CMakeFiles/map_manager.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j6 -l6" failed
请问如何解决？我查找了您的原代码，确实没有这个头文件

**Comment by Zhefan-Xu** [comment]
Could you please provide the way to reproduce the issue?
