### ISSUE TITLE
Error in file call

### ISSUE THREAD

**Issue by yangzhongii** [Zhefan-Xu/map_manager#7]
Thank you to the author for opening up such a perfect job. However, I encountered an error when calling the corresponding file according to your tutorial document. According to the document, replace the corresponding topic with the one on my robot. But when I replaced it, the map data corresponding to occupency_map could not be displayed on rviz, and the terminal could not display any errors. Afterwards, I made modifications according to the camera's display size, which were consistent with yours, but still couldn't be displayed. When I used rostopic echo to read the corresponding point cloud data, I found that the corresponding data was inconsistent with yours. It repeatedly displays the header:
seq: 120
stamp: 
secs: 0
nsecs:         0
frame_id: "odom"
height: 1
width: 0
fields: 
- 
name: "x"
offset: 0
datatype: 7
count: 1
- 
name: "y"
offset: 4
datatype: 7
count: 1
- 
name: "z"
offset: 8
datatype: 7
count: 1
is_bigendian: False
point_step: 16
row_step: 0
data: []
is_dense: True
And the data has not changed. The data format generated by my three topics is consistent with yours. I didn't know there was a problem there. I hope you can help me answer this question and answer in your spare time. I would greatly appreciate it.

**Comment by Zhefan-Xu** [comment]
Could you provide your config file?
